const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    description: "High-quality sound with noise cancellation.",
    image: "https://example.com/images/headphones.jpg",
    price: 99.99,
  },
  {
    id: 2,
    name: "Smartwatch",
    description: "Track your fitness and notifications on the go.",
    image: "https://example.com/images/smartwatch.jpg",
    price: 149.99,
  },
  {
    id: 3,
    name: "Laptop",
    description: "Lightweight laptop with powerful performance.",
    image: "https://example.com/images/laptop.jpg",
    price: 899.99,
  },
  {
    id: 4,
    name: "Gaming Mouse",
    description: "Precision control for an enhanced gaming experience.",
    image: "https://example.com/images/gaming_mouse.jpg",
    price: 49.99,
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    description: "Portable speaker with deep bass and 12-hour battery life.",
    image: "https://example.com/images/bluetooth_speaker.jpg",
    price: 59.99,
  },
  {
    id: 6,
    name: "Tablet",
    description: "10-inch screen with vibrant colors and fast performance.",
    image: "https://example.com/images/tablet.jpg",
    price: 299.99,
  },
  {
    id: 7,
    name: "4K TV",
    description: "Ultra HD smart TV with stunning visuals.",
    image: "https://example.com/images/tv.jpg",
    price: 799.99,
  },
  {
    id: 8,
    name: "Smart Light Bulb",
    description: "Control lighting with your voice or phone.",
    image: "https://example.com/images/smart_light_bulb.jpg",
    price: 19.99,
  },
  {
    id: 9,
    name: "Fitness Tracker",
    description: "Monitor your activity and heart rate with ease.",
    image: "https://example.com/images/fitness_tracker.jpg",
    price: 89.99,
  },
  {
    id: 10,
    name: "Drone",
    description: "Capture stunning aerial footage with a 4K camera.",
    image: "https://example.com/images/drone.jpg",
    price: 499.99,
  },
];
